# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: dev-to-master

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  Send-pr-to-master:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install
          npm i concurrently
          npm i wait-on

      # - name: Build Test
      #   run: npm run build
      - name: Run Storybook
        run: npm run build-storybook
      - name: Run Storybook Test
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue"
          npx http-server storybook-static --port 6006 --silent
          npx wait-on tcp:6006 && npm test-storybook

      - name: Create Pull Request On 'Dev'
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: `PR From ${repo}`,
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'master',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
