# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: dev-to-master

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build Test
        run: npm run build

  TestStorybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install concurrently wait-on
          npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Storybook Test
        run: npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "npm run storybook" "npx wait-on tcp:6006 && npm run test-storybook"

  prToMaster:
    needs: [Build, TestStorybook]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request On 'Dev'
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{github.token}}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: `PR From ${repo}`,
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'master',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
