# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: dev-to-master

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  Send-pr-to-master:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm
        run: npm install

      - name: Build Test
        run: npm build

      - name: UI Test
        run: npm test-storybook

      - name: Create Pull Request On 'Dev'
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: `PR From ${repo}`,
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'master',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
