name: devBack-to-dev

on:
  push:
    branches: ['dev-back-*']

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:
  test-jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run Test
        run: npm test

  pr-and-merge-to-dev:
    needs: [test-jest]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request On 'Dev'
        uses: actions/github-script@v6
        with:
          github-token: ${{github.token}}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: `pr From ${repo}`,
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'dev',
              body: "automated pr by github action. jest test done."
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr']
            });
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number:result.data.number
            });
