name: devFront-to-dev

on:
  push:
    branches: ['dev-front-*']

permissions:
  actions: read
  contents: write
  security-events: write
  pull-requests: write

jobs:
  test-storybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install concurrently wait-on
          npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Storybook Test
        run: npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "npm run storybook" "npx wait-on tcp:6006 && npm run test-storybook"

  pr-and-merge-to-dev:
    needs: [test-storybook]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request On 'Dev'
        uses: actions/github-script@v6
        with:
          github-token: ${{github.token}}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: `pr From ${repo}`,
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'dev',
              body: "automated pr by github action. Storybook test done"
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr']
            });
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number:result.data.number
            });
